# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170510_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='accounts/user.png', upload_to='accounts/'),
            preserve_default=False,
        ),
    ]
