# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='accounts/user.png', upload_to='accounts/'),
        ),
    ]
