# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170518_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='NO JOB', max_length=255),
            preserve_default=False,
        ),
    ]
