# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_hint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together=set([('challenge', 'text')]),
        ),
    ]
