# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20170504_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='challenges.Challenge'),
        ),
    ]
