# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20170504_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='nome allegato', max_length=256),
            preserve_default=False,
        ),
    ]
