# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0006_attachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='solved_by',
            field=models.ManyToManyField(related_name='solved_challenges', through='challenges.ChallengeSolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
