# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0008_challengefail'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='failed_by',
            field=models.ManyToManyField(related_name='failed_challenges', through='challenges.ChallengeFail', to=settings.AUTH_USER_MODEL),
        ),
    ]
