# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='challenges'),
        ),
    ]
